Tabs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include('mainApp.urls')),
    path(r'accounts/', include('accounts.urls')),
]

accounts/urls.py
from django.urls import path, re_path
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = 'accounts'

urlpatterns = [
    re_path(r'sign_up/', views.sign_up_view , name = 'sign_up_page'),
    re_path(r'log_in/', views.log_in_view , name = 'log_in_page'),
    re_path(r'log_out/', views.log_out_view , name = 'log_out_page')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mainApp/urls.py
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = 'mainApp'

urlpatterns = [
    re_path(r'^$', views.main_page, name = 'main_page'),
    re_path(r'^artists/$', views.view_page, name = 'view_page'),
    re_path(r'^artists/(?P<pk>\d+)/albums/$', views.albums_page, name='albums_page'),
    re_path(r'^artists/(?P<pk>\d+)/albums/songs/$', views.songs_page, name = 'songs_page'),
    re_path(r'^profile/(?P<pk>\d+)/personal_area/$', views.personal_area_page, name = 'personal_area_page'),
    path(r'about/', views.about_page, name='about_page'),
    path(r'contact/', views.contact_page, name = 'contact_page'),
    path(r'new_artist/', views.new_artist_page, name = 'new_artist_page'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

mainApp/models.py
from django.db import models

# Create your models here.

class Artist(models.Model):
    artist_name = models.CharField(max_length=100)
    info = models.TextField(default='n/a', max_length=400)

    def __str__(self):
        return self.artist_name

class Album(models.Model):
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    album_name = models.CharField(max_length=100)
    album_info = models.TextField(default='n/a', max_length=400)

    def __str__(self):
        return "%s | %s" % (self.album_name , self.artist)

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    number = models.IntegerField(default=0)
    song_name = models.CharField(max_length=100)
    link = models.CharField(max_length=300)

    def __str__(self):
        return "%s | %s" % (self.song_name, self.album)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
@csrf_exempt
def sign_up_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            #login user
            login(request, user)
            return redirect('mainApp:view_page')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/sign_up_page.html', {'form':form})

@csrf_exempt
def log_in_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #login user
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('mainApp:view_page')
    else:
        form = AuthenticationForm()

    return render(request, 'accounts/log_in_page.html', {'form':form})

@csrf_exempt
def log_out_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('mainApp:view_page')
    return render(request, 'accounts/log_out_page.html', {})

mainApp/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from .models import Artist, Album, Song

# Create your views here.


def main_page(request):
    return render(request, 'mainApp/main_page.html', {})


def view_page(request):
    artists = Artist.objects.filter(id__gt=0)
    return render(request, 'mainApp/view_page2.html', {'artists':artists})


def albums_page(request, pk):
    albums = Album.objects.filter(artist_id=pk)
    return render(request, 'mainApp/albums_page.html', {'albums': albums})


def songs_page(request, pk):
    songs = Song.objects.filter(album_id=pk)
    return render(request, 'mainApp/songs_page.html', {'songs': songs})


def about_page(request):
    return render(request, 'mainApp/about_page.html', {})


def contact_page(request):
    return render(request, 'mainApp/contact_page.html', {})

@login_required(login_url="/accounts/log_in/")
def personal_area_page(request):
    return render(request, 'mainApp/personal_area_page.html', {})

@login_required(login_url="/accounts/log_in/" )
def new_artist_page(request):
    return render(request, 'mainApp/new_artist_page.html', {})

accounts/templates/accounts/base_accounts.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>About</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "css/round-about.css" %}" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
          <a class="navbar-brand" href="{% url "mainApp:main_page" %}"><strong>Ez Tabs</strong></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
              <li class="nav-item">
              <a class="btn btn-primary" href="{% url "accounts:log_in_page" %}">Login</a>
            </li>
              <li class="nav-item active">
              <a class="nav-link" href="{% url "mainApp:view_page" %}">Artists
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "mainApp:contact_page" %}">Contact</a>
            </li>
              <li class="nav-item">
              <form class="logout-link" action="{% url "accounts:log_out_page" %}" method="post">
                {% csrf_token %}
                  <a class="btn btn-primary" href="{% url "mainApp:view_page" %}">Logout</a>
              </form>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">
        <br>
        <br>
        <br>
        {% block content %}
        {% endblock %}

    </div>
    <!-- /.container -->



    <!-- Bootstrap core JavaScript -->
    <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
    <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

  </body>

</html>

accounts/templates/accounts/log_in_page.html
{% extends 'accounts/base_accounts.html' %}

{% block content %}
    <form class="site-form" action={% url 'accounts:log_in_page' %} method="post">
    {% csrf_token %}
    {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <input type="submit" value="Login">
    </form>
    <p>Are you not signed up? <a href="{% url 'accounts:sign_up_page' %}">Sign up now!</a></p>
{% endblock %}

accounts/templates/accounts/log_out_page.html
{% extends 'accounts/base_accounts.html' %}

{% block content %}
    <p class="lead'">Wait a bit.</p>
{% endblock %}

accounts/templates/accounts/sign_up_page.html
{% extends 'accounts/base_accounts.html' %}

{% block content %}
    <form class="site-form" action="/accounts/sign_up/" method="post">
    {% csrf_token %}
    {{ form }}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

mainApp/templates/mainApp/about_page.html
{% extends 'mainApp/mainApp_base.html' %}
{% load staticfiles %}
{% block content %}

      <!-- Introduction Row -->
      <br>
        <br>
        <h1 class="my-4">About Us
        <small>It's Nice to Meet You!</small>
      </h1>
      <p>Well it's my first website all-by-myself made and actually made just for me, but it's something as for beginner</p>

      <!-- Team Members Row -->
      <div class="row">
        <div class="col-lg-4 col-sm-6 text-center mb-4">
          <img class="rounded-circle img-fluid d-block mx-auto" src="http://placehold.it/200x200" alt="">
          <h3>Vlad Novitsky
            <small>No job</small>
          </h3>
          <p>Done all that.</p>
        </div>
      </div>

{% endblock %}

mainApp/templates/mainApp/albums_page.html
{% extends 'mainApp/mainApp_base.html' %}
{% load staticfiles %}
{% block content %}
      <!-- Page Heading -->
        <h1 class="my-4"><strong>{{ albums.last }}</strong></h1>

      <div class="row">
          {% for album in albums %}
          <div class="col-lg-6 portfolio-item">
          <div class="card h-100">
            <a href="{% url "mainApp:songs_page"  pk=album.pk %}">
                <img class="card-img-top" src= "{% static "img/alb/" %}{{ album.pk }}.jpg" alt="ALBUM_IMG">
            </a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="{% url "mainApp:songs_page" pk=album.pk %}">{{ album.album_name }}</a>
              </h4>
              <p class="card-text">{{ album.album_info }}</p>
            </div>
          </div>
          </div>
          {% empty %}
            <div class="col-lg-12 text-center">
          <h1 class="mt-5">Oops, there's nothing there for now</h1>
          <p class="lead">Seems it's still empty as you see</p>
          </ul>
        </div>
          {% endfor %}
      <br>
      </div>
      <!-- /.row -->
{% endblock %}

mainApp/templates/mainApp/contact_page.html
{% extends 'mainApp/mainApp_base.html' %}
{% load staticfiles %}
{% block content %}
    <br>
      <div class="row">
        <div class="col-lg-12 text-center">
          <h1 class="mt-5">Contacts</h1>
          <p class="lead">If you have some advices or proposals just send me e-mail</p>
          <ul class="list-unstyled">
            <li>E-mail : novitsky.vladislav00@gmail.com</li>
            <li></li>
          </ul>
        </div>
      </div>
{% endblock %}

mainApp/templates/mainApp/mainApp_base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Artists</title>

    <!-- Bootstrap core CSS -->
    <link href="{%  static "vendor/bootstrap/css/bootstrap.min.css"%}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{%  static "css/1-col-portfolio.css" %}" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
          <a class="navbar-brand" href="{%  url "mainApp:main_page" %}"><strong>Ez Tabs</strong></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
              <li class="nav-item">
              <a class="btn btn-primary" href="{% url "accounts:sign_up_page" %}">Sign up</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "mainApp:about_page" %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "mainApp:contact_page" %}">Contact</a>
            </li>
              <li class="nav-item">
              <a class="btn btn-primary" href="{% url "accounts:log_in_page" %}">Login</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">

        {% block content %}
        {% endblock %}

    </div>
    <!-- /.container -->



    <!-- Bootstrap core JavaScript -->
    <script src="{%  static "vendor/jquery/jquery.min.js"%}"></script>
    <script src="{%  static "vendor/bootstrap/js/bootstrap.bundle.min.js"%}"></script>

  </body>

</html>

mainApp/templates/mainApp/main_page.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Ez Tabs</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "css/full.css" %}" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-bottom">
      <div class="container">
          <a class="navbar-brand" href="{% url "main_page" %}"><strong>Ez Tabs</strong></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url "view_page" %}">Artists
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "about_page" %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "contact_page" %}">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <section>
      <div class="container">
        <div class="row">
          <div class="col-lg-6">
              <h1 class="mt-5" style="color: white"><strong>Ez Tabs</strong></h1>
              <p style="color: white"><strong> This is webpage to search and open tabs ez and comfortable</strong></p>
          </div>
        </div>
      </div>
    </section>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
    <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

  </body>

</html>

mainApp/templates/mainApp/new_artist_page.html
{% extends 'mainApp/mainApp_base.html' %}
{% load staticfiles %}
{% block content %}
    <br>
    <br>
    <br>
    <h1>Check content</h1>
{% endblock %}

mainApp/templates/mainApp/personal_area_page.html
{% extends 'mainApp/mainApp_base.html' %}
{% load staticfiles %}
{% block content %}

{% endblock %}

mainApp/templates/mainApp/songs_page.html
{% extends 'mainApp/mainApp_base.html' %}
{% load staticfiles %}
{% block content %}
        <br>
        <br>
        <br>
        {% for song in songs %}
            <ul class="list-group">
                <a href="{{ song.link }}" class="list-group-item list-group-item-action">{{ song.song_name }}</a>
            </ul>
        {% empty %}
            <div class="col-lg-12 text-center">
          <h1 class="mt-5">Oops, there's nothing there for now</h1>
          <p class="lead">Seems it's still empty as you see</p>
          </ul>
        </div>
            <br>
        {% endfor %}
{% endblock %}

mainApp/templates/mainApp/view_page.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Ez Tabs</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "css/2-col-portfolio.css" %}" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="{% url "main_page" %}">Ez Tabs</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "about_page" %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "contact_page" %}">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">

      <!-- Page Heading -->
      <h1 class="my-4">Artists
      </h1>

    <div class="row">
        {% for artist in artists %}
        <div class="col-lg-6 portfolio-item">
          <div class="card h-100">
              {% load static %}
            <a href="{% static "#" %}"><img class="card-img-top" src="../../static/img/avatars/{{ artist.id }}.jpg" alt="PLACEHOLDER"></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="{% static "#" %}">{{ artist.artist_name }}</a>
              </h4>
            </div>
          </div>
        </div>
        </div>
    {% endfor %}


    </div>




    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Thnx for coming</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
    <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

  </body>

</html>

mainApp/templates/mainApp/view_page2.html
{% extends 'mainApp/mainApp_base.html' %}
{% load staticfiles %}
{% block content %}
    <!-- Page Content -->
    <div class="container">
      <!-- Page Heading -->
      <h1 class="my-4"><br></h1>

      <!-- Project One -->
        {% for artist in artists %}
        <div class="row">
          <div class="col-md-7">
          <a href="{% url "mainApp:albums_page" pk=artist.pk %}">
            <img class="img-fluid rounded mb-3 mb-md-0" src="../../static/img/avatars/{{ artist.pk }}.jpg" alt="ARTIST_IMG">
          </a>
        </div>
        <div class="col-md-5">
          <h3>{{ artist.artist_name }}</h3>
          <p>{{ artist.info }}</p>
          <a class="btn btn-primary" href="{% url "mainApp:albums_page" pk=artist.pk %}">View Albums</a>
        </div>
      </div>
      <!-- /.row -->

      <hr>
        {% endfor %}
    {% endblock %}